development: &default
  adapter: postgresql
  database: expense_manager_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: expense_manager_test
